<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;

class DestinationsSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            ['from_code'=>'BGW','from_name_ar'=>'بغداد','from_name_en'=>'Baghdad','to_code'=>'IST','to_name_ar'=>'إسطنبول','to_name_en'=>'Istanbul','slug'=>'baghdad-istanbul','flight_duration'=>'2h 45m','best_time_ar'=>'أبريل — أكتوبر','best_time_en'=>'April — October','description_ar'=>'رحلة بغداد إسطنبول من أكثر الرحلات شعبية. إسطنبول مدينة تجمع بين التاريخ العريق والحداثة.','description_en'=>'Baghdad to Istanbul is one of the most popular routes. Istanbul blends rich history with modernity.'],
            ['from_code'=>'BGW','from_name_ar'=>'بغداد','from_name_en'=>'Baghdad','to_code'=>'DXB','to_name_ar'=>'دبي','to_name_en'=>'Dubai','slug'=>'baghdad-dubai','flight_duration'=>'2h 15m','best_time_ar'=>'نوفمبر — مارس','best_time_en'=>'November — March','description_ar'=>'دبي وجهة التسوق والترفيه الأولى في الخليج. رحلات يومية من بغداد.','description_en'=>'Dubai is the premier shopping and entertainment destination in the Gulf. Daily flights from Baghdad.'],
            ['from_code'=>'BGW','from_name_ar'=>'بغداد','from_name_en'=>'Baghdad','to_code'=>'LHR','to_name_ar'=>'لندن','to_name_en'=>'London','slug'=>'baghdad-london','flight_duration'=>'6h 30m','best_time_ar'=>'مايو — سبتمبر','best_time_en'=>'May — September','description_ar'=>'لندن عاصمة الضباب والتاريخ. رحلات مباشرة وغير مباشرة من بغداد.','description_en'=>'London, the city of fog and history. Direct and connecting flights from Baghdad.'],
            ['from_code'=>'BGW','from_name_ar'=>'بغداد','from_name_en'=>'Baghdad','to_code'=>'FRA','to_name_ar'=>'فرانكفورت','to_name_en'=>'Frankfurt','slug'=>'baghdad-frankfurt','flight_duration'=>'5h 20m','best_time_ar'=>'أبريل — أكتوبر','best_time_en'=>'April — October','description_ar'=>'فرانكفورت بوابة أوروبا ومركز الأعمال الأكبر في ألمانيا.','description_en'=>'Frankfurt is the gateway to Europe and Germany\'s largest business hub.'],
            ['from_code'=>'BGW','from_name_ar'=>'بغداد','from_name_en'=>'Baghdad','to_code'=>'CAI','to_name_ar'=>'القاهرة','to_name_en'=>'Cairo','slug'=>'baghdad-cairo','flight_duration'=>'3h 00m','best_time_ar'=>'طوال العام','best_time_en'=>'Year-round','description_ar'=>'القاهرة مدينة الحضارات. أهرامات الجيزة والتاريخ الفرعوني بانتظارك.','description_en'=>'Cairo, the city of civilizations. The Giza Pyramids and Pharaonic history await.'],
            ['from_code'=>'AMM','from_name_ar'=>'عمّان','from_name_en'=>'Amman','to_code'=>'DXB','to_name_ar'=>'دبي','to_name_en'=>'Dubai','slug'=>'amman-dubai','flight_duration'=>'2h 50m','best_time_ar'=>'أكتوبر — مارس','best_time_en'=>'October — March','description_ar'=>'دبي وجهة مثالية لرحلات العمل والترفيه من عمّان.','description_en'=>'Dubai is ideal for business and leisure trips from Amman.'],
            ['from_code'=>'AMM','from_name_ar'=>'عمّان','from_name_en'=>'Amman','to_code'=>'LHR','to_name_ar'=>'لندن','to_name_en'=>'London','slug'=>'amman-london','flight_duration'=>'5h 30m','best_time_ar'=>'يونيو — أغسطس','best_time_en'=>'June — August','description_ar'=>'لندن من أكثر الوجهات شعبية للأردنيين. رحلات مباشرة يومياً.','description_en'=>'London is one of the most popular destinations for Jordanians. Daily direct flights.'],
            ['from_code'=>'RUH','from_name_ar'=>'الرياض','from_name_en'=>'Riyadh','to_code'=>'IST','to_name_ar'=>'إسطنبول','to_name_en'=>'Istanbul','slug'=>'riyadh-istanbul','flight_duration'=>'3h 30m','best_time_ar'=>'مارس — نوفمبر','best_time_en'=>'March — November','description_ar'=>'إسطنبول وجهة مفضلة للسعوديين بتجربة ثقافية لا مثيل لها.','description_en'=>'Istanbul is a favorite destination for Saudis with an unrivaled cultural experience.'],
            ['from_code'=>'RUH','from_name_ar'=>'الرياض','from_name_en'=>'Riyadh','to_code'=>'CDG','to_name_ar'=>'باريس','to_name_en'=>'Paris','slug'=>'riyadh-paris','flight_duration'=>'6h 45m','best_time_ar'=>'أبريل — أكتوبر','best_time_en'=>'April — October','description_ar'=>'باريس مدينة الأنوار والموضة والفن. رحلات مباشرة من الرياض.','description_en'=>'Paris, the city of lights, fashion and art. Direct flights from Riyadh.'],
            ['from_code'=>'CAI','from_name_ar'=>'القاهرة','from_name_en'=>'Cairo','to_code'=>'CDG','to_name_ar'=>'باريس','to_name_en'=>'Paris','slug'=>'cairo-paris','flight_duration'=>'5h 30m','best_time_ar'=>'مايو — سبتمبر','best_time_en'=>'May — September','description_ar'=>'باريس من أكثر الوجهات المحبوبة لدى المصريين. رحلات يومية من القاهرة.','description_en'=>'Paris is one of the most beloved destinations for Egyptians. Daily flights from Cairo.'],
            ['from_code'=>'DXB','from_name_ar'=>'دبي','from_name_en'=>'Dubai','to_code'=>'JFK','to_name_ar'=>'نيويورك','to_name_en'=>'New York','slug'=>'dubai-newyork','flight_duration'=>'14h 00m','best_time_ar'=>'سبتمبر — نوفمبر','best_time_en'=>'September — November','description_ar'=>'نيويورك المدينة التي لا تنام. رحلات مباشرة من دبي مع طيران الإمارات.','description_en'=>'New York, the city that never sleeps. Direct flights from Dubai with Emirates.'],
            ['from_code'=>'DXB','from_name_ar'=>'دبي','from_name_en'=>'Dubai','to_code'=>'LHR','to_name_ar'=>'لندن','to_name_en'=>'London','slug'=>'dubai-london','flight_duration'=>'7h 20m','best_time_ar'=>'مايو — أغسطس','best_time_en'=>'May — August','description_ar'=>'لندن وجهة لا غنى عنها للمسافرين من دبي. رحلات متعددة يومياً.','description_en'=>'London is a must-visit for Dubai travelers. Multiple daily flights.'],
            ['from_code'=>'KWI','from_name_ar'=>'الكويت','from_name_en'=>'Kuwait','to_code'=>'IST','to_name_ar'=>'إسطنبول','to_name_en'=>'Istanbul','slug'=>'kuwait-istanbul','flight_duration'=>'3h 15m','best_time_ar'=>'أبريل — أكتوبر','best_time_en'=>'April — October','description_ar'=>'إسطنبول وجهة ترفيهية وتسويقية مميزة من الكويت.','description_en'=>'Istanbul is a great leisure and shopping destination from Kuwait.'],
            ['from_code'=>'AUH','from_name_ar'=>'أبوظبي','from_name_en'=>'Abu Dhabi','to_code'=>'LHR','to_name_ar'=>'لندن','to_name_en'=>'London','slug'=>'abudhabi-london','flight_duration'=>'8h 00m','best_time_ar'=>'مايو — سبتمبر','best_time_en'=>'May — September','description_ar'=>'لندن وجهة العائلات والأعمال من أبوظبي. رحلات مباشرة مع الاتحاد.','description_en'=>'London is a family and business destination from Abu Dhabi. Direct flights with Etihad.'],
            ['from_code'=>'BEY','from_name_ar'=>'بيروت','from_name_en'=>'Beirut','to_code'=>'CDG','to_name_ar'=>'باريس','to_name_en'=>'Paris','slug'=>'beirut-paris','flight_duration'=>'4h 15m','best_time_ar'=>'أبريل — سبتمبر','best_time_en'=>'April — September','description_ar'=>'باريس تربطها علاقة خاصة ببيروت. رحلات مباشرة مع طيران الشرق الأوسط.','description_en'=>'Paris has a special connection with Beirut. Direct flights with Middle East Airlines.'],
            ['from_code'=>'MCT','from_name_ar'=>'مسقط','from_name_en'=>'Muscat','to_code'=>'DXB','to_name_ar'=>'دبي','to_name_en'=>'Dubai','slug'=>'muscat-dubai','flight_duration'=>'1h 20m','best_time_ar'=>'أكتوبر — مارس','best_time_en'=>'October — March','description_ar'=>'دبي أقرب وجهة ترفيهية وتسويقية من مسقط.','description_en'=>'Dubai is the closest entertainment and shopping destination from Muscat.'],
            ['from_code'=>'BGW','from_name_ar'=>'بغداد','from_name_en'=>'Baghdad','to_code'=>'VIE','to_name_ar'=>'فيينا','to_name_en'=>'Vienna','slug'=>'baghdad-vienna','flight_duration'=>'5h 00m','best_time_ar'=>'مايو — سبتمبر','best_time_en'=>'May — September','description_ar'=>'فيينا عاصمة الموسيقى والثقافة الأوروبية.','description_en'=>'Vienna, the capital of music and European culture.'],
            ['from_code'=>'RUH','from_name_ar'=>'الرياض','from_name_en'=>'Riyadh','to_code'=>'MAN','to_name_ar'=>'مانشستر','to_name_en'=>'Manchester','slug'=>'riyadh-manchester','flight_duration'=>'7h 30m','best_time_ar'=>'يونيو — أغسطس','best_time_en'=>'June — August','description_ar'=>'مانشستر مدينة كرة القدم والتعليم المفضلة لدى السعوديين.','description_en'=>'Manchester, city of football and education, a favorite for Saudis.'],
            ['from_code'=>'CAI','from_name_ar'=>'القاهرة','from_name_en'=>'Cairo','to_code'=>'JFK','to_name_ar'=>'نيويورك','to_name_en'=>'New York','slug'=>'cairo-newyork','flight_duration'=>'11h 30m','best_time_ar'=>'سبتمبر — نوفمبر','best_time_en'=>'September — November','description_ar'=>'نيويورك المدينة العالمية الأولى. رحلات من القاهرة عبر محطات متعددة.','description_en'=>'New York, the world\'s premier city. Flights from Cairo via multiple hubs.'],
            ['from_code'=>'BGW','from_name_ar'=>'بغداد','from_name_en'=>'Baghdad','to_code'=>'AMS','to_name_ar'=>'أمستردام','to_name_en'=>'Amsterdam','slug'=>'baghdad-amsterdam','flight_duration'=>'5h 45m','best_time_ar'=>'أبريل — أكتوبر','best_time_en'=>'April — October','description_ar'=>'أمستردام مدينة القنوات والتيوليب والتاريخ الأوروبي العريق.','description_en'=>'Amsterdam, the city of canals, tulips, and rich European history.'],
        ];

        $i = 1;
        foreach ($destinations as $dest) {
            Destination::updateOrCreate(
                ['slug' => $dest['slug']],
                array_merge($dest, [
                    'sort_order'        => $i++,
                    'meta_title'        => "رحلات {$dest['from_name_ar']} — {$dest['to_name_ar']} | أرخص الأسعار",
                    'meta_description'  => "احجز رحلتك من {$dest['from_name_ar']} إلى {$dest['to_name_ar']} بأفضل الأسعار. قارن مئات شركات الطيران واحجز فوراً.",
                ])
            );
        }
    }
}
